// Generated by unRap v1.06 by Kegetys

class CfgAddons {
	class PreloadAddons {
		class A3_Warlords {
			list[] = {"A3_Data_F_Warlords_Loadorder", "A3_Data_F_Warlords", "A3_Dubbing_F_Warlords", "A3_Functions_F_Warlords", "A3_Language_F_Warlords", "A3_Missions_F_Warlords", "A3_Modules_F_Warlords"};
		};
	};
};
