// Generated by unRap v1.06 by Kegetys

class CfgMods {
	class Mod_Base;	// External class reference
	
	class Warlords : Mod_Base {
		dir = "Warlords";
		name = "Arma 3 Warlords";
		author = "$STR_A3_Bohemia_Interactive";
		tooltip = "Arma 3 Warlords DLC now available. Click to purchase";
		tooltipOwned = "Arma 3 Warlords";
		overview = "Do stuff in Arma 3 Warlords Update.";
		action = "https://www.arma3.com/";
		dlcColor[] = {1.0, 0.55, 0.0.30, 1};
		picture = "\A3\Data_F_Warlords\Logos\arma3_Warlords_icon_ca.paa";
		logo = "\A3\Data_F_Warlords\Logos\arma3_Warlords_logo_ca.paa";
		logoOver = "\A3\Data_F_Warlords\Logos\arma3_Warlords_logoOver_ca.paa";
		logoSmall = "\A3\Data_F_Warlords\Logos\arma3_Warlords_logo_small_ca.paa";
	};
};
