// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class A3_Missions_F_Warlords_Data {
		author = "$STR_A3_Bohemia_Interactive";
		name = "CFGPATCHES_A3_Missions_F_Warlords_Data";
		url = "http://www.arma3.com";
		requiredAddons[] = {"A3_Missions_F_Warlords"};
		requiredVersion = 0.1;
		units[] = {};
		weapons[] = {};
	};
};
