// Generated by unRap v1.06 by Kegetys

class CfgHints {
	class WarlordsUpdate {
		category = "Product";
		displayName = "$STR_A3_WL_modUpdate";
		logicalOrder = 15;
		
		class Warlords {
			arguments[] = {{"<img size='9' shadow='0' color='#ffffff' image='A3\Data_F_Warlords\Data\wl_logo_ca.paa' />"}};
			displayName = "$STR_A3_WL_modName";
			description = "$STR_A3_WL_modDescription";
			image = "\a3\ui_f\data\gui\cfg\hints\Commanding_ca.paa";
		};
	};
};
