// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class A3_Language_F_Warlords {
		author = "$STR_A3_Bohemia_Interactive";
		name = "Arma 3 Warlords - Texts and Translations";
		url = "http://www.arma3.com";
		requiredAddons[] = {"A3_Language_F_Tank"};
		requiredVersion = 0.1;
		units[] = {};
		weapons[] = {};
	};
};
