// Generated by unRap v1.06 by Kegetys

class CfgFunctions {
	class A3_Warlords {
		tag = BIS;
		project = "arma3";
		
		class Warlords {
			file = "A3\Functions_F_Warlords\Warlords";
			
			class WLAICore {
				ext = ".fsm";
			};
			
			class WLAIPathSegmentation {};
			
			class WLAIPurchases {
				ext = ".fsm";
			};
			
			class WLAircraftArrival {};
			
			class WLAirdrop {};
			
			class WLAISectorScan {};
			
			class WLCalculateIncome {};
			
			class WLCalculateSectorConnections {};
			
			class WLClientInit {};
			
			class WLDebug {};
			
			class WLDefenceSetup {};
			
			class WLDropPurchase {};
			
			class WLFundsInfo {};
			
			class WLGarrisonRetreat {
				ext = ".fsm";
			};
			
			class WLInit {};
			
			class WLInSectorArea {};
			
			class WLLoadoutApply {};
			
			class WLLoadoutGrab {};
			
			class WLMostVotedSector {};
			
			class WLNavalArrival {};
			
			class WLOpenArsenal {};
			
			class WLOSD {};
			
			class WLOutlineIcons {};
			
			class WLPlayersTracking {};
			
			class WLPlayersTrackingServer {};
			
			class WLPurchaseMenu {};
			
			class WLRandomPosRect {};
			
			class WLRecalculateServices {};
			
			class WLRemovalHandle {};
			
			class WLReputation {};
			
			class WLRequestFastTravel {};
			
			class WLRequestFundsTransfer {};
			
			class WLRequestPurchase {};
			
			class WLRequestSectorScan {};
			
			class WLRequestVotingReset {};
			
			class WLSectorFundsPayoff {
				ext = ".fsm";
			};
			
			class WLSectorHandle {
				ext = ".fsm";
			};
			
			class WLSectorHandleServer {
				ext = ".fsm";
			};
			
			class WLSectorIconUpdate {};
			
			class WLSectorInit {};
			
			class WLSectorListing {};
			
			class WLSectorPopulate {};
			
			class WLSectorScanHandle {
				ext = ".fsm";
			};
			
			class WLSectorsCommonInit {};
			
			class WLSectorSelectionEnd {};
			
			class WLSectorSelectionHandle {
				ext = ".fsm";
			};
			
			class WLSectorSelectionHandleServer {
				ext = ".fsm";
			};
			
			class WLSectorSelectionStart {};
			
			class WLSectorsSetup {};
			
			class WLSectorTaskHandle {
				ext = ".fsm";
			};
			
			class WLSectorUpdate {};
			
			class WLSeizingBarHandle {};
			
			class WLSendResponseTeam {};
			
			class WLShowInfo {};
			
			class WLSideToFaction {};
			
			class WLSoundMsg {};
			
			class WLSubroutine_purchaseMenuAssetAvailability {};
			
			class WLSubroutine_purchaseMenuGetUIScale {};
			
			class WLSubroutine_purchaseMenuHandleDLC {};
			
			class WLSubroutine_purchaseMenuRefresh {};
			
			class WLSubroutine_purchaseMenuSetAssetDetails {};
			
			class WLSubroutine_purchaseMenuSetItemsList {};
			
			class WLSyncTime {};
			
			class WLUpdateAO {};
			
			class WLVarsInit {};
			
			class WLVehicleHandle {};
			
			class WLVotingBarHandle {};
		};
		
		class Misc {
			file = "A3\Functions_F_Warlords\Misc";
			
			class WLSmoothText {};
		};
	};
};
