// Generated by unRap v1.06 by Kegetys

class CfgDebriefing {
	class BIS_WLVictoryWEST {
		title = "$STR_A3_endgame_debriefing_victory";
		subtitle = "$STR_A3_WL_game_over_victory";
		picture = "b_installation";
		pictureBackground = "\A3\Map_Altis\data\ui_Altis_ca.paa";
		pictureColor[] = {0.0, 0.3, 0.6, 1};
	};
	
	class BIS_WLVictoryEAST : BIS_WLVictoryWEST {
		picture = "o_installation";
		pictureColor[] = {0.5, 0.0, 0.0, 1};
	};
	
	class BIS_WLDefeatWEST {
		title = "$STR_A3_endgame_debriefing_defeat";
		subtitle = "$STR_A3_WL_game_over_loss";
		picture = "b_installation";
		pictureBackground = "\A3\Map_Altis\data\ui_Altis_ca.paa";
		pictureColor[] = {0.0, 0.3, 0.6, 1};
	};
	
	class BIS_WLDefeatEAST : BIS_WLDefeatWEST {
		picture = "o_installation";
		pictureColor[] = {0.5, 0.0, 0.0, 1};
	};
};
