// Generated by unRap v1.06 by Kegetys

class CfgMPGameTypes {
	class Warlords {
		featured = 1;
		id = 23;
		name = "$STR_A3_WL_modName";
		shortcut = "$STR_A3_WL_modName";
		description = "";
		picture = "\a3\Data_F_Warlords\Data\wl_logo_ca.paa";
	};
};
