// Generated by unRap v1.06 by Kegetys

class CfgMissions {
	class MPMissions {
		class MP_Warlords_official_01 {
			briefingName = "$STR_A3_WL_scenario_name_2";
			overviewText = "$STR_A3_WL_modRules";
			overview = "A3\Data_F_Warlords\Data\wl_logo_ca.paa";
			directory = "A3\Missions_F_Warlords\MPScenarios\MP_Warlords_01.Altis";
		};
		
		class MP_Warlords_official_01a : MP_Warlords_official_01 {
			briefingName = "$STR_A3_WL_scenario_name_4";
			directory = "A3\Missions_F_Warlords\MPScenarios\MP_Warlords_01a.Altis";
		};
		
		class MP_Warlords_official_01b : MP_Warlords_official_01a {
			briefingName = "$STR_A3_WL_scenario_name_5";
			directory = "A3\Missions_F_Warlords\MPScenarios\MP_Warlords_01b.Altis";
		};
		
		class MP_Warlords_official_02 : MP_Warlords_official_01 {
			briefingName = "$STR_A3_WL_scenario_name_1";
			directory = "A3\Missions_F_Warlords\MPScenarios\MP_Warlords_02.Stratis";
		};
		
		class MP_Warlords_official_03 : MP_Warlords_official_01 {
			briefingName = "$STR_A3_WL_scenario_name_6";
			directory = "A3\Missions_F_Warlords\MPScenarios\MP_Warlords_03.Tanoa";
		};
		
		class MP_Warlords_official_03a : MP_Warlords_official_01 {
			briefingName = "$STR_A3_WL_scenario_name_7";
			directory = "A3\Missions_F_Warlords\MPScenarios\MP_Warlords_03a.Tanoa";
		};
		
		class MP_Warlords_official_04 : MP_Warlords_official_01 {
			briefingName = "$STR_A3_WL_scenario_name_1";
			directory = "A3\Missions_F_Warlords\MPScenarios\MP_Warlords_04.Malden";
		};
	};
};
