// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class A3_Data_F_Warlords_Loadorder {
		addonRootClass = "A3_Data_F_Warlords";
		requiredAddons[] = {"A3_Data_F_Warlords", "A3_Dubbing_F_Warlords", "A3_Functions_F_Warlords", "A3_Language_F_Warlords", "A3_Missions_F_Warlords", "A3_Modules_F_Warlords"};
		requiredVersion = 0.1;
		units[] = {};
		weapons[] = {};
	};
};
