// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class Logic;	// External class reference
	
	class Module_F : Logic {
		class AttributesBase {
			class Default;	// External class reference
			class Edit;	// External class reference
			class Combo;	// External class reference
			class Checkbox;	// External class reference
			class CheckboxNumber;	// External class reference
			class ModuleDescription;	// External class reference
			class Units;	// External class reference
		};
		
		class ModuleDescription {
			class AnyBrain;	// External class reference
		};
	};
	
	class ModuleWLTemplate_F : Module_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "ModuleWLTemplate_F";
		scope = private;
		category = "Warlords";
		isTriggerActivated = 0;
		isDisposable = 0;
	};
	
	class ModuleWLInit_F : ModuleWLTemplate_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "ModuleWLInit_F";
		scope = public;
		icon = "A3\Data_F_Warlords\Data\wl_module_i_ca.paa";
		displayName = "$STR_A3_WL_module_init_name";
		function = "BIS_fnc_WLInit";
		isGlobal = 2;
		
		class Attributes : AttributesBase {
			class Progress : Combo {
				property = "ModuleWLInit_F_Progress";
				displayName = "$STR_A3_WL_param1_title";
				tooltip = "$STR_A3_WL_param1_desc";
				typeName = NUMBER;
				defaultValue = "1";
				
				class Values {
					class Progress_0 {
						name = "$STR_special_none";
						value = 1;
					};
					
					class Progress_1 {
						name = "$STR_A3_WL_forcedProgress_perc_1";
						value = 2;
					};
					
					class Progress_2 {
						name = "$STR_A3_WL_forcedProgress_perc_2";
						value = 3;
					};
					
					class Progress_3 {
						name = "$STR_A3_WL_forcedProgress_perc_3";
						value = 4;
					};
					
					class Progress_4 {
						name = "$STR_A3_WL_forcedProgress_perc_4";
						value = 5;
					};
					
					class Progress_5 {
						name = "$STR_A3_WL_forcedProgress_perc_5";
						value = 6;
					};
					
					class Progress_6 {
						name = "$STR_A3_WL_forcedProgress_perc_6";
						value = 7;
					};
					
					class Progress_7 {
						name = "$STR_A3_WL_forcedProgress_perc_7";
						value = 8;
					};
					
					class Progress_8 {
						name = "$STR_A3_WL_forcedProgress_perc_8";
						value = 9;
					};
					
					class Progress_9 {
						name = "$STR_A3_WL_forcedProgress_perc_9";
						value = 10;
					};
					
					class Progress_10 {
						name = "$STR_A3_WL_forcedProgress_perc_10";
						value = 11;
					};
					
					class Progress_11 {
						name = "$STR_A3_WL_forcedProgress_perc_11";
						value = 12;
					};
					
					class Progress_12 {
						name = "$STR_A3_WL_forcedProgress_perc_12";
						value = 13;
					};
				};
			};
			
			class TimeAcceleration : Combo {
				property = "ModuleWLInit_F_TimeAcceleration";
				displayName = "$STR_A3_WL_param2_title";
				tooltip = "";
				typeName = NUMBER;
				defaultValue = "1";
				
				class Values {
					class TimeAcc_0 {
						name = "$STR_special_none";
						value = 1;
					};
					
					class TimeAcc_2 {
						name = "x2";
						value = 2;
					};
					
					class TimeAcc_4 {
						name = "x4";
						value = 4;
					};
					
					class TimeAcc_6 {
						name = "x6";
						value = 6;
					};
					
					class TimeAcc_8 {
						name = "x8";
						value = 8;
					};
					
					class TimeAcc_10 {
						name = "x10";
						value = 10;
					};
					
					class TimeAcc_12 {
						name = "x12";
						value = 12;
					};
					
					class TimeAcc_14 {
						name = "x14";
						value = 14;
					};
					
					class TimeAcc_16 {
						name = "x16";
						value = 16;
					};
					
					class TimeAcc_18 {
						name = "x18";
						value = 18;
					};
					
					class TimeAcc_20 {
						name = "x20";
						value = 20;
					};
					
					class TimeAcc_22 {
						name = "x22";
						value = 22;
					};
					
					class TimeAcc_24 {
						name = "x24";
						value = 24;
					};
				};
			};
			
			class FTEnabled : Combo {
				property = "ModuleWLInit_F_FTEnabled";
				displayName = "$STR_A3_fastravel1";
				tooltip = "$STR_A3_WL_param3_desc";
				typeName = NUMBER;
				defaultValue = "1";
				
				class Values {
					class Enabled {
						name = "$STR_A3_WL_param3_value1";
						value = 1;
					};
					
					class Disabled {
						name = "$STR_A3_WL_param3_value2";
						value = 0;
					};
					
					class DisabledAI {
						name = "$STR_A3_WL_param3_value3";
						value = 2;
					};
					
					class DisabledPlayers {
						name = "$STR_A3_WL_param3_value4";
						value = 3;
					};
					
					class OwnedOnly {
						name = "$STR_A3_WL_param3_value5";
						value = 4;
					};
				};
			};
			
			class ScanEnabled : CheckboxNumber {
				property = "ModuleWLInit_F_ScanEnabled";
				displayName = "$STR_A3_WL_param4_title";
				tooltip = "$STR_A3_WL_param4_desc";
				typeName = NUMBER;
				defaultValue = "1";
			};
			
			class AIVoting : CheckboxNumber {
				property = "ModuleWLInit_F_AIVoting";
				displayName = "$STR_A3_WL_param5_title";
				tooltip = "$STR_A3_WL_param5_desc";
				typeName = NUMBER;
				defaultValue = "0";
			};
			
			class ArsenalEnabled : CheckboxNumber {
				property = "ModuleWLInit_F_ArsenalEnabled";
				displayName = "$STR_A3_Arsenal";
				tooltip = "$STR_A3_WL_param6_desc";
				typeName = NUMBER;
				defaultValue = "1";
			};
			
			class VotingResetEnabled : CheckboxNumber {
				property = "ModuleWLInit_F_VotingResetEnabled";
				displayName = "$STR_A3_WL_menu_resetvoting";
				tooltip = "$STR_A3_WL_menu_resetvoting_desc";
				typeName = NUMBER;
				defaultValue = "0";
			};
			
			class MarkersTransparency : Combo {
				property = "ModuleWLInit_F_MarkersTransparency";
				displayName = "$STR_A3_WL_param7_title";
				tooltip = "$STR_A3_WL_param7_desc";
				typeName = NUMBER;
				defaultValue = "2";
				
				class Values {
					class T1 {
						name = "$STR_A3_WL_param7_value1";
						value = 4;
					};
					
					class T2 {
						name = "$STR_A3_WL_markerAlpha_perc_1";
						value = 3;
					};
					
					class T3 {
						name = "$STR_A3_WL_markerAlpha_perc_2";
						value = 2;
					};
					
					class T4 {
						name = "$STR_A3_WL_markerAlpha_perc_3";
						value = 1;
					};
					
					class T5 {
						name = "$STR_A3_WL_param7_value2";
						value = 0;
					};
				};
			};
			
			class PlayersTransparency : Combo {
				property = "ModuleWLInit_F_PlayersTransparency";
				displayName = "$STR_A3_WL_param8_title";
				tooltip = "$STR_A3_WL_param8_desc";
				typeName = NUMBER;
				defaultValue = "2";
				
				class Values {
					class T1 {
						name = "$STR_A3_WL_param7_value1";
						value = 4;
					};
					
					class T2 {
						name = "$STR_A3_WL_markerAlpha_perc_1";
						value = 3;
					};
					
					class T3 {
						name = "$STR_A3_WL_markerAlpha_perc_2";
						value = 2;
					};
					
					class T4 {
						name = "$STR_A3_WL_markerAlpha_perc_3";
						value = 1;
					};
					
					class T5 {
						name = "$STR_A3_WL_param7_value2";
						value = 0;
					};
				};
			};
			
			class FatigueEnabled : CheckboxNumber {
				property = "ModuleWLInit_F_FatigueEnabled";
				displayName = "$STR_A3_fatigue1";
				tooltip = "$STR_A3_WL_param9_desc";
				typeName = NUMBER;
				defaultValue = "1";
			};
			
			class Music : CheckboxNumber {
				property = "ModuleWLInit_F_Music";
				displayName = "$STR_A3_rscattributemusic_title";
				tooltip = "$STR_A3_WL_param10_desc";
				typeName = NUMBER;
				defaultValue = "1";
			};
			
			class Voice : CheckboxNumber {
				property = "ModuleWLInit_F_Voice";
				displayName = "$STR_A3_orange_faction_idap_cfgidentities_expo_name";
				tooltip = "$STR_A3_WL_param11_desc";
				typeName = NUMBER;
				defaultValue = "1";
			};
			
			class StartCP : Combo {
				property = "ModuleWLInit_F_StartCP";
				displayName = "$STR_A3_WL_param12_title";
				tooltip = "$STR_A3_WL_param12_desc";
				typeName = NUMBER;
				defaultValue = 500;
				
				class Values {
					class CP1 {
						name = "0";
						value = 0;
					};
					
					class CP2 {
						name = 100;
						value = 100;
					};
					
					class CP3 {
						name = 250;
						value = 250;
					};
					
					class CP4 {
						name = 500;
						value = 500;
					};
					
					class CP5 {
						name = 1000;
						value = 750;
					};
					
					class CP6 {
						name = 2500;
						value = 2500;
					};
					
					class CP7 {
						name = 5000;
						value = 5000;
					};
				};
			};
			
			class CPMultiplier : Combo {
				property = "ModuleWLInit_F_CPMultiplier";
				displayName = "$STR_A3_WL_param13_title";
				tooltip = "$STR_A3_WL_param13_desc";
				typeName = NUMBER;
				defaultValue = "1";
				
				class Values {
					class CP1 {
						name = "1x";
						value = 1;
					};
					
					class CP2 {
						name = "2x";
						value = 2;
					};
					
					class CP3 {
						name = "3x";
						value = 3;
					};
					
					class CP4 {
						name = "4x";
						value = 4;
					};
					
					class CP5 {
						name = "5x";
						value = 5;
					};
				};
			};
			
			class VotingTimeout : Combo {
				property = "ModuleWLInit_F_VotingTimeout";
				displayName = "$STR_A3_WL_param14_title";
				tooltip = "$STR_A3_WL_param14_desc";
				typeName = NUMBER;
				defaultValue = "15";
				
				class Values {
					class TO1 {
						name = "5";
						value = 5;
					};
					
					class TO2 {
						name = "10";
						value = 10;
					};
					
					class TO3 {
						name = "15";
						value = 15;
					};
					
					class TO4 {
						name = "20";
						value = 20;
					};
					
					class TO5 {
						name = "25";
						value = 25;
					};
					
					class TO6 {
						name = "30";
						value = 30;
					};
				};
			};
			
			class VehicleSpan : Combo {
				property = "ModuleWLInit_F_VehicleSpan";
				displayName = "$STR_A3_WL_param15_title";
				tooltip = "$STR_A3_WL_param15_desc";
				typeName = NUMBER;
				defaultValue = 3600;
				
				class Values {
					class TO1 {
						name = "15";
						value = 900;
					};
					
					class TO2 {
						name = "30";
						value = 1800;
					};
					
					class TO3 {
						name = "60";
						value = 3600;
					};
					
					class TO4 {
						name = "90";
						value = 5400;
					};
					
					class TO5 {
						name = 120;
						value = 7200;
					};
					
					class TO6 {
						name = "$STR_A3_WL_param15_value1";
						value = 1000000;
					};
				};
			};
			
			class FactionBLUFOR : Edit {
				property = "ModuleWLInit_F_FactionBLUFOR";
				displayName = "$STR_A3_WL_param16_title";
				tooltip = "$STR_A3_WL_param16_desc";
				typeName = STRING;
				defaultValue = """BLU_F""";
			};
			
			class FactionOPFOR : Edit {
				property = "ModuleWLInit_F_FactionOPFOR";
				displayName = "$STR_A3_WL_param17_title";
				tooltip = "$STR_A3_WL_param16_desc";
				typeName = STRING;
				defaultValue = """OPF_F""";
			};
			
			class FactionIndep : Edit {
				property = "ModuleWLInit_F_FactionIndep";
				displayName = "$STR_A3_WL_param18_title";
				tooltip = "$STR_A3_WL_param16_desc";
				typeName = STRING;
				defaultValue = """IND_F""";
			};
			
			class AssetList : Edit {
				property = "ModuleWLInit_F_AssetList";
				displayName = "$STR_A3_WL_param19_title";
				tooltip = "$STR_A3_WL_param19_desc";
				defaultValue = """['A3DefaultAll']""";
			};
			
			class MissionEnd : CheckboxNumber {
				property = "ModuleWLInit_F_MissionEnd";
				displayName = "$STR_A3_WL_param20_title";
				tooltip = "$STR_A3_WL_param20_desc";
				typeName = NUMBER;
				defaultValue = "1";
			};
			
			class DebriefingWinBLUFOR : Edit {
				property = "ModuleWLInit_F_DebriefingWinBLUFOR";
				displayName = "$STR_A3_WL_param21_title";
				tooltip = "$STR_A3_WL_param21_desc";
				typeName = STRING;
				defaultValue = """BIS_WLVictoryWEST""";
			};
			
			class DebriefingFailBLUFOR : Edit {
				property = "ModuleWLInit_F_DebriefingFailBLUFOR";
				displayName = "$STR_A3_WL_param22_title";
				tooltip = "$STR_A3_WL_param21_desc";
				typeName = STRING;
				defaultValue = """BIS_WLDefeatWEST""";
			};
			
			class DebriefingWinOPFOR : Edit {
				property = "ModuleWLInit_F_DebriefingWinOPFOR";
				displayName = "$STR_A3_WL_param23_title";
				tooltip = "$STR_A3_WL_param21_desc";
				typeName = STRING;
				defaultValue = """BIS_WLVictoryEAST""";
			};
			
			class DebriefingFailOPFOR : Edit {
				property = "ModuleWLInit_F_DebriefingFailOPFOR";
				displayName = "$STR_A3_WL_param24_title";
				tooltip = "$STR_A3_WL_param21_desc";
				typeName = STRING;
				defaultValue = """BIS_WLDefeatEAST""";
			};
			
			class ModuleDescription : ModuleDescription {};
		};
		
		class ModuleDescription : ModuleDescription {
			description = "$STR_A3_WL_moduleDesc_init";
		};
	};
	
	class ModuleWLBase_F : ModuleWLTemplate_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "ModuleWLBase_F";
		scope = public;
		icon = "A3\Data_F_Warlords\Data\wl_module_b_ca.paa";
		displayName = "$STR_A3_WL_module_base_name";
		function = "";
		isGlobal = 2;
		
		class Attributes : AttributesBase {
			class Name : Edit {
				property = "ModuleWLBase_F_Name";
				displayName = "$STR_A3_combatpatrol_modules_4";
				tooltip = "$STR_A3_WL_param25_desc";
				defaultValue = """""";
			};
			
			class LocationName : Checkbox {
				property = "ModuleWLBase_F_LocationName";
				displayName = "$STR_A3_WL_param36_title";
				tooltip = "$STR_A3_WL_param36_desc";
				typeName = BOOL;
				defaultValue = FALSE;
			};
			
			class Side : Combo {
				property = "ModuleWLBase_F_Side";
				displayName = "$STR_eval_typeside";
				tooltip = "$STR_A3_WL_param26_desc";
				typeName = NUMBER;
				defaultValue = "2";
				
				class Values {
					class BLUFOR {
						name = "$STR_west";
						value = 2;
					};
					
					class OPFOR {
						name = "$STR_east";
						value = 1;
					};
				};
			};
			
			class Size : Edit {
				property = "ModuleWLBase_F_Size";
				displayName = "$STR_A3_mp_groundsupport_modulemptypegroundsupportbase_size";
				tooltip = "$STR_A3_WL_param27_desc";
				typeName = NUMBER;
				defaultValue = 250;
			};
			
			class Funds : Edit {
				property = "ModuleWLBase_F_Funds";
				displayName = "$STR_A3_WL_param28_title";
				tooltip = "$STR_A3_WL_param28_desc";
				typeName = NUMBER;
				defaultValue = "10";
			};
			
			class SeizingTime : Edit {
				property = "ModuleWLBase_F_SeizingTime";
				displayName = "$STR_A3_WL_param29_title";
				tooltip = "$STR_A3_WL_param29_desc";
				typeName = NUMBER;
				defaultValue = "0";
			};
			
			class Service_Harbour : Checkbox {
				property = "ModuleWLBase_F_Service_Harbour";
				displayName = "$STR_A3_WL_param30_title";
				tooltip = "$STR_A3_WL_param30_desc";
				typeName = BOOL;
				defaultValue = FALSE;
			};
			
			class Service_Helipad : Checkbox {
				property = "ModuleWLBase_F_Service_Helipad";
				displayName = "$STR_A3_WL_module_service_helipad";
				tooltip = "$STR_A3_WL_param31_desc";
				typeName = BOOL;
				defaultValue = FALSE;
			};
			
			class Service_Runway : Checkbox {
				property = "ModuleWLBase_F_Service_Runway";
				displayName = "$STR_A3_WL_param32_title";
				tooltip = "$STR_A3_WL_param32_desc";
				typeName = BOOL;
				defaultValue = FALSE;
			};
			
			class ModuleDescription : ModuleDescription {};
		};
		
		class ModuleDescription : ModuleDescription {
			description = "$STR_A3_WL_moduleDesc_base";
			position = 1;
			duplicate = 1;
		};
	};
	
	class ModuleWLSector_F : ModuleWLTemplate_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "ModuleWLSector_F";
		scope = public;
		icon = "A3\Data_F_Warlords\Data\wl_module_s_ca.paa";
		displayName = "$STR_A3_WL_module_sector_name";
		function = "";
		isGlobal = 2;
		
		class Attributes : AttributesBase {
			class Name : Edit {
				property = "ModuleWLSector_F_Name";
				displayName = "$STR_A3_combatpatrol_modules_4";
				tooltip = "$STR_A3_WL_param25_desc";
				defaultValue = """""";
			};
			
			class LocationName : Checkbox {
				property = "ModuleWLSector_F_LocationName";
				displayName = "$STR_A3_WL_param36_title";
				tooltip = "$STR_A3_WL_param36_desc";
				typeName = BOOL;
				defaultValue = TRUE;
			};
			
			class Side : Combo {
				property = "ModuleWLSector_F_Side";
				displayName = "$STR_eval_typeside";
				tooltip = "$STR_A3_WL_param26_desc_b";
				typeName = NUMBER;
				defaultValue = "0";
				
				class Values {
					class Default {
						name = "$STR_disp_default";
						value = 0;
					};
					
					class BLUFOR {
						name = "$STR_west";
						value = 2;
					};
					
					class OPFOR {
						name = "$STR_east";
						value = 1;
					};
				};
			};
			
			class Size : Edit {
				property = "ModuleWLSector_F_Size";
				displayName = "$STR_A3_mp_groundsupport_modulemptypegroundsupportbase_size";
				tooltip = "$STR_A3_WL_param27_desc";
				typeName = NUMBER;
				defaultValue = 250;
			};
			
			class Funds : Edit {
				property = "ModuleWLSector_F_Funds";
				displayName = "$STR_A3_WL_param28_title";
				tooltip = "$STR_A3_WL_param28_desc";
				typeName = NUMBER;
				defaultValue = "25";
			};
			
			class SeizingTime : Edit {
				property = "ModuleWLSector_F_SeizingTime";
				displayName = "$STR_A3_WL_param29_title";
				tooltip = "$STR_A3_WL_param29_desc";
				typeName = NUMBER;
				defaultValue = "0";
			};
			
			class Service_Harbour : Checkbox {
				property = "ModuleWLSector_F_Service_Harbour";
				displayName = "$STR_A3_WL_param30_title";
				tooltip = "$STR_A3_WL_param30_desc";
				typeName = BOOL;
				defaultValue = FALSE;
			};
			
			class Service_Helipad : Checkbox {
				property = "ModuleWLSector_F_Service_Helipad";
				displayName = "$STR_A3_WL_module_service_helipad";
				tooltip = "$STR_A3_WL_param31_desc";
				typeName = BOOL;
				defaultValue = FALSE;
			};
			
			class Service_Runway : Checkbox {
				property = "ModuleWLSector_F_Service_Runway";
				displayName = "$STR_A3_WL_param32_title";
				tooltip = "$STR_A3_WL_param32_desc";
				typeName = BOOL;
				defaultValue = FALSE;
			};
			
			class FastTravelEnabled : Checkbox {
				property = "ModuleWLSector_F_FastTravelEnabled";
				displayName = "$STR_A3_fastravel1";
				tooltip = "$STR_A3_WL_param33_desc";
				typeName = BOOL;
				defaultValue = TRUE;
			};
			
			class ModuleDescription : ModuleDescription {};
		};
		
		class ModuleDescription : ModuleDescription {
			description = "$STR_A3_WL_moduleDesc_sector";
			position = 1;
			duplicate = 1;
		};
	};
	
	class ModuleWLResponse_F : ModuleWLTemplate_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "ModuleWLResponse_F";
		scope = public;
		icon = "A3\Data_F_Warlords\Data\wl_module_rt_ca.paa";
		displayName = "$STR_A3_WL_module_response_name";
		function = "";
		isGlobal = 0;
		
		class Attributes : AttributesBase {
			class Group : Combo {
				property = "ModuleWLResponse_F_Group";
				displayName = "$STR_brief_group";
				tooltip = "$STR_A3_WL_param34_desc";
				typeName = NUMBER;
				defaultValue = "0";
				
				class Values {
					class Random {
						name = "$STR_A3_bis_fnc_respawnmenuposition_random";
						value = 0;
					};
					
					class Sync {
						name = "$STR_A3_WL_param34_value1";
						value = 1;
					};
					
					class Inf {
						name = "$STR_A3_cfgmarkers_nato_inf";
						value = 2;
					};
					
					class Mech {
						name = "$STR_A3_cfgmarkers_nato_mech_inf";
						value = 3;
					};
					
					class Moto {
						name = "$STR_A3_cfgmarkers_nato_motor_inf";
						value = 4;
					};
					
					class Armor {
						name = "$STR_A3_cfgmarkers_nato_armor";
						value = 5;
					};
					
					class Airdrop {
						name = "$STR_A3_WL_param34_value2";
						value = 6;
					};
				};
			};
			
			class ModuleDescription : ModuleDescription {};
		};
		
		class ModuleDescription : ModuleDescription {
			description = "$STR_A3_WL_moduleDesc_response";
			position = 1;
			duplicate = 1;
		};
	};
	
	class ModuleWLSpawnPoint_F : ModuleWLTemplate_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "ModuleWLSpawnPoint_F";
		scope = public;
		icon = "A3\Data_F_Warlords\Data\wl_module_sp_ca.paa";
		displayName = "$STR_A3_WL_module_spawn_name";
		function = "";
		isGlobal = 0;
		
		class Attributes : AttributesBase {
			class ModuleDescription : ModuleDescription {};
		};
		
		class ModuleDescription : ModuleDescription {
			description = "$STR_A3_WL_moduleDesc_spawn";
			position = 1;
			duplicate = 1;
		};
	};
};
